repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests before commit
        entry: uv run test
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: check-python-syntax
        name: Check Python syntax
        entry: python -m py_compile
        language: system
        files: \.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
