repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests before push
        entry: uv run test
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: check-python-syntax
        name: Check Python syntax
        entry: python -m py_compile
        language: system
        files: \.py$
        stages: [pre-push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-push]
      - id: end-of-file-fixer
        stages: [pre-push]
      - id: check-yaml
        stages: [pre-push]
      - id: check-added-large-files
        stages: [pre-push]
      - id: check-merge-conflict
        stages: [pre-push]
