[project]
name = "news-notify"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.55",
    "pytest>=8.4.2",
    "requests>=2.32.5",
]
