AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Notify Tech News

Parameters:
  WebhookUrl:
    Type: String


Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  NewsNotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: news-notify-function
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          WEBHOOK_URL: !Ref WebhookUrl
      # Events:
      #   NewsNotify:
      #     Type: Api
      #     Properties:
      #       Path: /hello
      #       Method: get
    
  NewsNotifyAppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: news_notify_app_table
      AttributeDefinitions:
        - AttributeName: title
          AttributeType: S
      KeySchema:
        - AttributeName: title
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expired_at_unix_time

Outputs:
  NewsNotifyFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt NewsNotifyFunction.Arn
  NewsNotifyTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref NewsNotifyAppTable
